name: Run Vertex AI Notebook
on:
  push:
    branches: [ master ]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create credential file
        run: |
          echo '${{ secrets.VAI_CREDENTIALS }}' > credential.json
          echo "CREDENTIAL_FILE=$(pwd)/credential.json" >> $GITHUB_ENV
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2.0.0'
        with:
          project_id: ${{ secrets.VAI_PROJECT_ID }}
          credentials_json: ${{ env.CREDENTIAL_FILE }}
      - name: Run Vertex AI Notebook
        uses: google-github-actions/run-vertexai-notebook@v0
        with:
          gcs_source_bucket: '${{ secrets.GCS_SOURCE }}'
          gcs_output_bucket: '${{ secrets.GCS_OUTPUT }}'
          allowlist: index-py
          region: us-east1