name: Run Vertex AI Notebook
on:
  push:
    branches: [ main ]
jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create credential file
        run: |
          echo '${{ secrets.VAI_CREDENTIALS }}' > credential.json
          echo "CREDENTIAL_FILE=$(pwd)/credential.json" >> $GITHUB_ENV
      - name: Run Vertex AI Notebook
        uses: google-github-actions/run-vertexai-notebook@main
        with:
          project_id: ${{ secrets.VAI_PROJECT_ID }}
          region: us-central1
          machine_type: n1-standard-4
          notebook_file: index.py
          credential_file: ${{ env.CREDENTIAL_FILE }}